version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    environment:
      DB_HOST: db
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

