version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    env_file:
      - .env

volumes:
  db_data:
